image: python:3.8

stages:
  - build

default:
  before_script:
    # - npm install --global yarn
    - apt-get install curl
    - curl -sL https://deb.nodesource.com/setup_14.x | bash -
    - apt-get install nodejs
    - pip3 install awscli
    - npm install yarn -g
    - yarn install

build-and-deploy:
  only:
    - develop
  stage: build
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
  script:
    - echo AWS_REGION="$AWS_REGION_DEV">>.env
    - yarn build

    - aws s3 cp ./dist s3://"$TrMIS_WEBAPP_DEV"/ --recursive --region "$AWS_REGION_DEV"
    - aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID_DEV" --paths "/*"


